export enum DateFormats {
  MonthDayCommaYear = 'MMMM DD, YYYY',
  ShortMonthDayCommaYear = 'MMM DD, YYYY',
  ShortMonthDayCommaTime = 'MMM dd, h:mm a',
  YearDashMonth = 'YYYY-MM',
  YearDashMonthDashDay = 'YYYY-MM-DD',
  ShortMonthDayCommaYearHourMinuteMeridiem = 'MMM DD, YYYY h:mm A',
  YearDashMonthDashDayHourMinuteSecond = 'YYYY-MM-DD HH:mm:ss',
  YearDashMonthDashDaySingleHourMinuteSecond = 'YYYY-MM-DD H:mm:ss',
  DayMonth = 'DD MMMM',
  Month = 'MMMM',
  ShortMonth = 'MMM',
  Day = 'DD',
  hhmmA = 'hh:mm A',
  hhmmssA = 'hh:mm:ss A',
  LongDayOfWeek = 'dddd',
  ShortMonthDayCommaYearHourMinuteSecondsMeridiem = 'MMM DD, YYYY hh:mm:ss A',
  Year = 'YYYY',
}
